# fashion_data.py
# 女装穿搭提示词生成器 - 完整数据库
# 约1000+条目，中英双语

CATEGORIES = [
    {
        "name": "风格方向",
        "icon": "🎨",
        "modules": [
            {
                "name": "经典风格",
                "key": "classic_style",
                "multi": True,
                "options": [
                    {"zh": "法式慵懒", "en": "french chic", "desc": "法式慵懒风格"},
                    {"zh": "意式优雅", "en": "italian elegance", "desc": "意式优雅风格"},
                    {"zh": "英伦学院", "en": "british preppy", "desc": "英伦学院风格"},
                    {"zh": "北欧极简", "en": "scandinavian minimal", "desc": "北欧极简风格"},
                    {"zh": "日式侘寂", "en": "japanese wabi-sabi", "desc": "日式侘寂风格"},
                    {"zh": "美式休闲", "en": "american casual", "desc": "美式休闲风格"},
                    {"zh": "新中式", "en": "new chinese style", "desc": "新中式风格"},
                    {"zh": "韩系清新", "en": "korean fresh", "desc": "韩系清新风格"},
                    {"zh": "波西米亚", "en": "bohemian", "desc": "波西米亚风格"},
                    {"zh": "复古优雅", "en": "vintage elegant", "desc": "复古优雅风格"},
                    {"zh": "古典浪漫", "en": "classical romantic", "desc": "古典浪漫风格"},
                    {"zh": "地中海风", "en": "mediterranean style", "desc": "地中海风格"},
                ],
            },
            {
                "name": "流行风格",
                "key": "trend_style",
                "multi": True,
                "options": [
                    {"zh": "极简利落风", "en": "clean fit aesthetic", "desc": "极简利落风格"},
                    {"zh": "老钱风", "en": "old money aesthetic", "desc": "老钱风格"},
                    {"zh": "静奢风", "en": "quiet luxury", "desc": "静奢风格"},
                    {"zh": "千禧风", "en": "y2k style", "desc": "千禧风格"},
                    {"zh": "多巴胺穿搭", "en": "dopamine dressing", "desc": "多巴胺穿搭风格"},
                    {"zh": "美拉德穿搭", "en": "maillard dressing", "desc": "美拉德穿搭风格"},
                    {"zh": "芭蕾风", "en": "balletcore", "desc": "芭蕾美学风格"},
                    {"zh": "娇俏风", "en": "coquette style", "desc": "娇俏风格"},
                    {"zh": "阔太风", "en": "mob wife aesthetic", "desc": "阔太贵妇风格"},
                    {"zh": "职场魅惑风", "en": "office siren", "desc": "职场魅惑风格"},
                    {"zh": "山系机能风", "en": "gorpcore outdoor", "desc": "山系机能风格"},
                    {"zh": "废土风", "en": "wasteland style", "desc": "废土风格"},
                    {"zh": "赛博朋克", "en": "cyberpunk", "desc": "赛博朋克风格"},
                    {"zh": "波希风", "en": "boho chic", "desc": "波希米亚风格"},
                    {"zh": "田园风", "en": "cottagecore", "desc": "乡村田园风格"},
                    {"zh": "暗黑学院风", "en": "dark academia", "desc": "暗黑学院风格"},
                    {"zh": "学院风", "en": "preppy style", "desc": "经典学院风格"},
                    {"zh": "颓废摇滚风", "en": "grunge style", "desc": "颓废摇滚风格"},
                    {"zh": "极简主义", "en": "minimalism", "desc": "极简主义风格"},
                    {"zh": "甜酷风", "en": "sweet and cool", "desc": "甜酷风格"},
                ],
            },
            {
                "name": "场景风格",
                "key": "scene_style",
                "multi": True,
                "options": [
                    {"zh": "约会甜系", "en": "date sweet style", "desc": "约会甜系风格"},
                    {"zh": "通勤干练", "en": "office chic", "desc": "通勤干练风格"},
                    {"zh": "度假放松", "en": "vacation relaxed", "desc": "度假放松风格"},
                    {"zh": "街头酷感", "en": "street cool", "desc": "街头酷感风格"},
                    {"zh": "居家慵懒", "en": "loungewear cozy", "desc": "居家慵懒风格"},
                    {"zh": "派对女王", "en": "party queen", "desc": "派对女王风格"},
                    {"zh": "运动休闲", "en": "athleisure", "desc": "运动休闲风格"},
                    {"zh": "艺术文艺", "en": "artistic literary", "desc": "艺术文艺风格"},
                    {"zh": "婚礼宴会", "en": "wedding banquet", "desc": "婚礼宴会风格"},
                    {"zh": "日常出行", "en": "daily casual", "desc": "日常出行风格"},
                    {"zh": "摄影写真", "en": "photo shoot", "desc": "摄影写真风格"},
                    {"zh": "毕业照", "en": "graduation photo", "desc": "毕业照风格"},
                ],
            },
            {
                "name": "季节风格",
                "key": "season_style",
                "multi": False,
                "options": [
                    {"zh": "春夏轻盈", "en": "spring-summer light", "desc": "春夏轻盈风格"},
                    {"zh": "秋冬温暖", "en": "fall-winter warm", "desc": "秋冬温暖风格"},
                    {"zh": "早春过渡", "en": "early spring transitional", "desc": "早春过渡风格"},
                    {"zh": "盛夏清凉", "en": "peak summer cool", "desc": "盛夏清凉风格"},
                ],
            },
        ],
    },
    {
        "name": "人物描述",
        "icon": "👤",
        "modules": [
            {
                "name": "肤色",
                "key": "skin_tone",
                "multi": False,
                "options": [
                    {"zh": "白皙", "en": "fair skin", "desc": "白皙肤色"},
                    {"zh": "自然白", "en": "light skin", "desc": "自然白肤色"},
                    {"zh": "自然肤色", "en": "natural skin tone", "desc": "自然肤色"},
                    {"zh": "小麦色", "en": "wheat skin", "desc": "小麦色肤色"},
                    {"zh": "古铜色", "en": "bronze skin", "desc": "古铜色肤色"},
                    {"zh": "健康蜜色", "en": "honey skin", "desc": "健康蜜色肤色"},
                ],
            },
            {
                "name": "肤调",
                "key": "skin_undertone",
                "multi": False,
                "options": [
                    {"zh": "冷调", "en": "cool undertone", "desc": "冷调肤色"},
                    {"zh": "暖调", "en": "warm undertone", "desc": "暖调肤色"},
                    {"zh": "中性调", "en": "neutral undertone", "desc": "中性调肤色"},
                    {"zh": "橄榄调", "en": "olive undertone", "desc": "橄榄调肤色"},
                ],
            },
            {
                "name": "体型",
                "key": "body_type",
                "multi": False,
                "options": [
                    {"zh": "纤细修长", "en": "slender figure", "desc": "纤细修长体型"},
                    {"zh": "匀称身材", "en": "balanced figure", "desc": "匀称身材"},
                    {"zh": "丰满曲线", "en": "curvy figure", "desc": "丰满曲线体型"},
                    {"zh": "梨形身材", "en": "pear-shaped body", "desc": "梨形身材"},
                    {"zh": "苹果型身材", "en": "apple-shaped body", "desc": "苹果型身材"},
                    {"zh": "沙漏型身材", "en": "hourglass figure", "desc": "沙漏型身材"},
                    {"zh": "高挑身材", "en": "tall slender", "desc": "高挑身材"},
                    {"zh": "娇小身材", "en": "petite figure", "desc": "娇小身材"},
                ],
            },
            {
                "name": "年龄感",
                "key": "age_range",
                "multi": False,
                "options": [
                    {"zh": "少女感", "en": "teens youthful", "desc": "少女感"},
                    {"zh": "轻熟风", "en": "young adult 20s", "desc": "轻熟风"},
                    {"zh": "成熟优雅", "en": "mature elegant 30s", "desc": "成熟优雅"},
                    {"zh": "知性大气", "en": "sophisticated 40s", "desc": "知性大气"},
                ],
            },
            {
                "name": "气质",
                "key": "aura",
                "multi": True,
                "options": [
                    {"zh": "甜美", "en": "sweet", "desc": "甜美气质"},
                    {"zh": "清纯", "en": "pure innocent", "desc": "清纯气质"},
                    {"zh": "性感", "en": "sexy", "desc": "性感气质"},
                    {"zh": "优雅", "en": "elegant", "desc": "优雅气质"},
                    {"zh": "帅气", "en": "handsome cool", "desc": "帅气气质"},
                    {"zh": "知性", "en": "intellectual", "desc": "知性气质"},
                    {"zh": "慵懒", "en": "languid", "desc": "慵懒气质"},
                    {"zh": "活泼", "en": "lively", "desc": "活泼气质"},
                    {"zh": "高冷", "en": "aloof cool", "desc": "高冷气质"},
                    {"zh": "温柔", "en": "gentle tender", "desc": "温柔气质"},
                ],
            },
        ],
    },
    {
        "name": "发型",
        "icon": "💇",
        "modules": [
            {
                "name": "发型长度",
                "key": "hair_length",
                "multi": False,
                "options": [
                    {"zh": "超短发", "en": "pixie cut", "desc": "超短发"},
                    {"zh": "短发", "en": "short hair bob", "desc": "短发"},
                    {"zh": "中长发", "en": "medium length hair", "desc": "中长发"},
                    {"zh": "长发", "en": "long hair", "desc": "长发"},
                    {"zh": "超长发", "en": "extra long hair", "desc": "超长发"},
                ],
            },
            {
                "name": "发型形态",
                "key": "hair_texture",
                "multi": False,
                "options": [
                    {"zh": "直发", "en": "straight hair", "desc": "直发"},
                    {"zh": "微卷", "en": "slightly wavy hair", "desc": "微卷发型"},
                    {"zh": "大波浪", "en": "big waves", "desc": "大波浪发型"},
                    {"zh": "卷发", "en": "curly hair", "desc": "卷发"},
                    {"zh": "羊毛卷", "en": "tight curls perm", "desc": "羊毛卷发型"},
                    {"zh": "水波纹", "en": "water wave hair", "desc": "水波纹发型"},
                    {"zh": "法式卷", "en": "french curls", "desc": "法式卷发"},
                ],
            },
            {
                "name": "扎发方式",
                "key": "hair_updo",
                "multi": False,
                "options": [
                    {"zh": "披散", "en": "hair down", "desc": "披散发型"},
                    {"zh": "高马尾", "en": "high ponytail", "desc": "高马尾"},
                    {"zh": "低马尾", "en": "low ponytail", "desc": "低马尾"},
                    {"zh": "丸子头", "en": "top knot bun", "desc": "丸子头"},
                    {"zh": "低发髻", "en": "low bun", "desc": "低发髻"},
                    {"zh": "高发髻", "en": "high bun", "desc": "高发髻"},
                    {"zh": "半扎发", "en": "half up half down", "desc": "半扎发"},
                    {"zh": "双马尾", "en": "twin tails", "desc": "双马尾"},
                    {"zh": "麻花辫", "en": "braid", "desc": "麻花辫"},
                    {"zh": "鱼骨辫", "en": "fishtail braid", "desc": "鱼骨辫"},
                    {"zh": "法式编发", "en": "french braid", "desc": "法式编发"},
                    {"zh": "盘发", "en": "updo", "desc": "盘发"},
                    {"zh": "侧边编发", "en": "side braid", "desc": "侧边编发"},
                ],
            },
            {
                "name": "刘海类型",
                "key": "bangs",
                "multi": False,
                "options": [
                    {"zh": "无刘海", "en": "no bangs", "desc": "无刘海"},
                    {"zh": "齐刘海", "en": "straight bangs", "desc": "齐刘海"},
                    {"zh": "空气刘海", "en": "wispy bangs", "desc": "空气刘海"},
                    {"zh": "八字刘海", "en": "curtain bangs", "desc": "八字刘海"},
                    {"zh": "法式刘海", "en": "french bangs", "desc": "法式刘海"},
                    {"zh": "斜刘海", "en": "side swept bangs", "desc": "斜刘海"},
                    {"zh": "眉上刘海", "en": "micro bangs", "desc": "眉上刘海"},
                    {"zh": "龙须刘海", "en": "face framing tendrils", "desc": "龙须刘海"},
                ],
            },
            {
                "name": "发色",
                "key": "hair_color",
                "multi": False,
                "options": [
                    {"zh": "黑色", "en": "black hair", "desc": "黑色头发"},
                    {"zh": "深棕色", "en": "dark brown hair", "desc": "深棕色头发"},
                    {"zh": "棕色", "en": "brown hair", "desc": "棕色头发"},
                    {"zh": "浅棕色", "en": "light brown hair", "desc": "浅棕色头发"},
                    {"zh": "金色", "en": "blonde hair", "desc": "金色头发"},
                    {"zh": "浅金色", "en": "platinum blonde hair", "desc": "浅金色头发"},
                    {"zh": "红色", "en": "red hair", "desc": "红色头发"},
                    {"zh": "粉色", "en": "pink hair", "desc": "粉色头发"},
                    {"zh": "蓝色", "en": "blue hair", "desc": "蓝色头发"},
                    {"zh": "紫色", "en": "purple hair", "desc": "紫色头发"},
                    {"zh": "渐变色", "en": "gradient hair", "desc": "渐变色头发"},
                    {"zh": "挑染", "en": "highlights", "desc": "挑染头发"},
                    {"zh": "灰棕色", "en": "ash brown hair", "desc": "灰棕色头发"},
                    {"zh": "奶茶色", "en": "milk tea hair color", "desc": "奶茶色头发"},
                ],
            },
        ],
    },
    {
        "name": "妆容",
        "icon": "💄",
        "modules": [
            {
                "name": "底妆",
                "key": "base_makeup",
                "multi": False,
                "options": [
                    {"zh": "裸妆", "en": "natural bare makeup", "desc": "裸妆底妆"},
                    {"zh": "哑光妆", "en": "matte finish makeup", "desc": "哑光妆底妆"},
                    {"zh": "水光妆", "en": "dewy glass skin", "desc": "水光妆底妆"},
                    {"zh": "奶油肌", "en": "cream skin finish", "desc": "奶油肌底妆"},
                    {"zh": "陶瓷肌", "en": "porcelain skin", "desc": "陶瓷肌底妆"},
                    {"zh": "韩系水光", "en": "korean glass skin", "desc": "韩系水光底妆"},
                    {"zh": "日系透明感", "en": "japanese transparent skin", "desc": "日系透明感底妆"},
                ],
            },
            {
                "name": "眼妆",
                "key": "eye_makeup",
                "multi": True,
                "options": [
                    {"zh": "自然眼妆", "en": "natural eye makeup", "desc": "自然眼妆"},
                    {"zh": "大地色系眼妆", "en": "earth tone eyeshadow", "desc": "大地色系眼妆"},
                    {"zh": "粉色系眼妆", "en": "pink eyeshadow", "desc": "粉色系眼妆"},
                    {"zh": "烟熏妆", "en": "smoky eyes", "desc": "烟熏眼妆"},
                    {"zh": "猫眼妆", "en": "cat eye makeup", "desc": "猫眼妆"},
                    {"zh": "桃花眼妆", "en": "peach blossom eyes", "desc": "桃花眼妆"},
                    {"zh": "微闪眼妆", "en": "shimmer eye makeup", "desc": "微闪眼妆"},
                    {"zh": "下眼影重点", "en": "lower eye emphasis", "desc": "下眼影重点妆容"},
                    {"zh": "单眼皮妆容", "en": "monolid makeup", "desc": "单眼皮妆容"},
                    {"zh": "截断式眼妆", "en": "cut crease eyeshadow", "desc": "截断式眼妆"},
                ],
            },
            {
                "name": "唇妆",
                "key": "lip_makeup",
                "multi": False,
                "options": [
                    {"zh": "裸粉色", "en": "nude pink lips", "desc": "裸粉色唇妆"},
                    {"zh": "正红色", "en": "classic red lips", "desc": "正红色唇妆"},
                    {"zh": "豆沙色", "en": "bean paste lips", "desc": "豆沙色唇妆"},
                    {"zh": "珊瑚色", "en": "coral lips", "desc": "珊瑚色唇妆"},
                    {"zh": "橘色", "en": "orange lips", "desc": "橘色唇妆"},
                    {"zh": "玫瑰色", "en": "rose lips", "desc": "玫瑰色唇妆"},
                    {"zh": "浆果色", "en": "berry lips", "desc": "浆果色唇妆"},
                    {"zh": "水光唇", "en": "glossy lips", "desc": "水光唇妆"},
                    {"zh": "复古红唇", "en": "vintage red lips", "desc": "复古红唇妆"},
                    {"zh": "渐变唇", "en": "gradient lips", "desc": "渐变唇妆"},
                ],
            },
            {
                "name": "腮红",
                "key": "blush",
                "multi": False,
                "options": [
                    {"zh": "自然腮红", "en": "natural blush", "desc": "自然腮红"},
                    {"zh": "粉色腮红", "en": "pink blush", "desc": "粉色腮红"},
                    {"zh": "橘色腮红", "en": "peach blush", "desc": "橘色腮红"},
                    {"zh": "微醺腮红", "en": "drunken blush", "desc": "微醺腮红"},
                    {"zh": "高位腮红", "en": "high placement blush", "desc": "高位腮红"},
                    {"zh": "无腮红", "en": "no blush", "desc": "无腮红"},
                ],
            },
            {
                "name": "修容高光",
                "key": "contour_highlight",
                "multi": True,
                "options": [
                    {"zh": "自然修容", "en": "natural contour", "desc": "自然修容"},
                    {"zh": "明显修容", "en": "scuplted contour", "desc": "明显修容"},
                    {"zh": "自然高光", "en": "natural highlight", "desc": "自然高光"},
                    {"zh": "水光高光", "en": "dewy highlight", "desc": "水光高光"},
                    {"zh": "珠光高光", "en": "shimmer highlight", "desc": "珠光高光"},
                    {"zh": "不修容", "en": "no contour", "desc": "不修容"},
                ],
            },
            {
                "name": "眉毛",
                "key": "eyebrow",
                "multi": False,
                "options": [
                    {"zh": "自然眉", "en": "natural brows", "desc": "自然眉形"},
                    {"zh": "野生眉", "en": "wild brows", "desc": "野生眉形"},
                    {"zh": "平直眉", "en": "straight brows", "desc": "平直眉形"},
                    {"zh": "弯月眉", "en": "arched brows", "desc": "弯月眉形"},
                    {"zh": "英气眉", "en": "strong brows", "desc": "英气眉形"},
                    {"zh": "柳叶眉", "en": "willow leaf brows", "desc": "柳叶眉形"},
                ],
            },
        ],
    },
    {
        "name": "上装",
        "icon": "👚",
        "modules": [
            {
                "name": "款式",
                "key": "top_type",
                "multi": False,
                "options": [
                    {"zh": "T恤", "en": "t-shirt", "desc": "T恤"},
                    {"zh": "衬衫", "en": "button-up shirt", "desc": "衬衫"},
                    {"zh": "针织衫", "en": "knit sweater", "desc": "针织衫"},
                    {"zh": "毛衣", "en": "sweater", "desc": "毛衣"},
                    {"zh": "卫衣", "en": "hoodie sweatshirt", "desc": "卫衣"},
                    {"zh": "吊带", "en": "cami top", "desc": "吊带上衣"},
                    {"zh": "背心", "en": "tank top", "desc": "背心"},
                    {"zh": "抹胸", "en": "tube top", "desc": "抹胸"},
                    {"zh": "露脐装", "en": "crop top", "desc": "露脐装"},
                    {"zh": "Polo衫", "en": "polo shirt", "desc": "Polo衫"},
                    {"zh": "连体衣", "en": "bodysuit", "desc": "连体衣"},
                    {"zh": "罩衫", "en": "blouse", "desc": "罩衫"},
                    {"zh": "Bralette", "en": "bralette", "desc": "Bralette"},
                    {"zh": "短上衣", "en": "cropped top", "desc": "短上衣"},
                    {"zh": "打底衫", "en": "base layer top", "desc": "打底衫"},
                    {"zh": "蕾丝上衣", "en": "lace top", "desc": "蕾丝上衣"},
                    {"zh": "荷叶边上衣", "en": "ruffle top", "desc": "荷叶边上衣"},
                    {"zh": "一字肩上衣", "en": "off-shoulder top", "desc": "一字肩上衣"},
                    {"zh": "方领上衣", "en": "square neck top", "desc": "方领上衣"},
                    {"zh": "高领衫", "en": "turtleneck top", "desc": "高领衫"},
                    {"zh": "开衫", "en": "cardigan", "desc": "开衫"},
                    {"zh": "马甲", "en": "vest top", "desc": "马甲"},
                    {"zh": "抹胸上衣", "en": "bandeau top", "desc": "抹胸上衣"},
                    {"zh": "长袖紧身衣", "en": "long sleeve fitted top", "desc": "长袖紧身衣"},
                    {"zh": "短袖紧身衣", "en": "short sleeve fitted top", "desc": "短袖紧身衣"},
                    {"zh": "露背上衣", "en": "open back top", "desc": "露背上衣"},
                    {"zh": "蝴蝶结上衣", "en": "bow top", "desc": "蝴蝶结上衣"},
                    {"zh": "褶皱上衣", "en": "pleated top", "desc": "褶皱上衣"},
                    {"zh": "透视上衣", "en": "sheer top", "desc": "透视上衣"},
                    {"zh": "系带上衣", "en": "tie front top", "desc": "系带上衣"},
                    {"zh": "公主袖上衣", "en": "puff sleeve top", "desc": "公主袖上衣"},
                    {"zh": "泡泡袖上衣", "en": "bubble sleeve top", "desc": "泡泡袖上衣"},
                ],
            },
            {
                "name": "领型",
                "key": "neckline",
                "multi": False,
                "options": [
                    {"zh": "圆领", "en": "round neck", "desc": "圆领设计"},
                    {"zh": "V领", "en": "v-neck", "desc": "V领设计"},
                    {"zh": "深V领", "en": "deep v-neck", "desc": "深V领设计"},
                    {"zh": "方领", "en": "square neck", "desc": "方领设计"},
                    {"zh": "一字领", "en": "boat neck", "desc": "一字领设计"},
                    {"zh": "高领", "en": "turtleneck", "desc": "高领设计"},
                    {"zh": "半高领", "en": "mock neck", "desc": "半高领设计"},
                    {"zh": "小高领", "en": "small mock neck", "desc": "小高领设计"},
                    {"zh": "翻领", "en": "collar", "desc": "翻领设计"},
                    {"zh": "立领", "en": "stand collar", "desc": "立领设计"},
                    {"zh": "Peter Pan领", "en": "peter pan collar", "desc": "Peter Pan领设计"},
                    {"zh": "心形领", "en": "sweetheart neckline", "desc": "心形领设计"},
                    {"zh": "斜肩", "en": "asymmetric shoulder", "desc": "斜肩设计"},
                    {"zh": "露肩", "en": "off-shoulder", "desc": "露肩设计"},
                    {"zh": "挂脖", "en": "halter neck", "desc": "挂脖设计"},
                    {"zh": "挂脖交叉", "en": "cross halter", "desc": "挂脖交叉设计"},
                    {"zh": "水手领", "en": "sailor collar", "desc": "水手领设计"},
                    {"zh": "U领", "en": "u-neck", "desc": "U领设计"},
                    {"zh": "匙形领", "en": "scoop neck", "desc": "匙形领设计"},
                    {"zh": "露肩荷叶边", "en": "off-shoulder ruffle", "desc": "露肩荷叶边设计"},
                    {"zh": "系带领", "en": "tie collar", "desc": "系带领设计"},
                    {"zh": "围裹领", "en": "wrap neckline", "desc": "围裹领设计"},
                    {"zh": "镂空领", "en": "cutout neckline", "desc": "镂空领设计"},
                ],
            },
            {
                "name": "袖型",
                "key": "sleeve_type",
                "multi": False,
                "options": [
                    {"zh": "长袖", "en": "long sleeves", "desc": "长袖设计"},
                    {"zh": "短袖", "en": "short sleeves", "desc": "短袖设计"},
                    {"zh": "七分袖", "en": "three-quarter sleeves", "desc": "七分袖设计"},
                    {"zh": "无袖", "en": "sleeveless", "desc": "无袖设计"},
                    {"zh": "泡泡袖", "en": "puff sleeves", "desc": "泡泡袖设计"},
                    {"zh": "灯笼袖", "en": "lantern sleeves", "desc": "灯笼袖设计"},
                    {"zh": "荷叶边袖", "en": "ruffle sleeves", "desc": "荷叶边袖设计"},
                    {"zh": "蝙蝠袖", "en": "batwing sleeves", "desc": "蝙蝠袖设计"},
                    {"zh": "喇叭袖", "en": "flare sleeves", "desc": "喇叭袖设计"},
                    {"zh": "落肩袖", "en": "drop shoulder sleeves", "desc": "落肩袖设计"},
                    {"zh": "插肩袖", "en": "raglan sleeves", "desc": "插肩袖设计"},
                    {"zh": "羊腿袖", "en": "leg-of-mutton sleeves", "desc": "羊腿袖设计"},
                    {"zh": "主教袖", "en": "bishop sleeves", "desc": "主教袖设计"},
                    {"zh": "开叉袖", "en": "split sleeves", "desc": "开叉袖设计"},
                    {"zh": "飞袖", "en": "cap sleeves", "desc": "飞袖设计"},
                    {"zh": "荷叶袖", "en": "flutter sleeves", "desc": "荷叶袖设计"},
                    {"zh": "花瓣袖", "en": "petal sleeves", "desc": "花瓣袖设计"},
                    {"zh": "堆堆袖", "en": "slouchy sleeves", "desc": "堆堆袖设计"},
                ],
            },
            {
                "name": "面料质感",
                "key": "fabric",
                "multi": False,
                "options": [
                    {"zh": "棉质", "en": "cotton fabric", "desc": "棉质面料"},
                    {"zh": "亚麻", "en": "linen fabric", "desc": "亚麻面料"},
                    {"zh": "真丝", "en": "silk fabric", "desc": "真丝面料"},
                    {"zh": "雪纺", "en": "chiffon fabric", "desc": "雪纺面料"},
                    {"zh": "蕾丝", "en": "lace fabric", "desc": "蕾丝面料"},
                    {"zh": "针织", "en": "knit fabric", "desc": "针织面料"},
                    {"zh": "牛仔", "en": "denim fabric", "desc": "牛仔面料"},
                    {"zh": "皮革", "en": "leather", "desc": "皮革面料"},
                    {"zh": "天鹅绒", "en": "velvet", "desc": "天鹅绒面料"},
                    {"zh": "缎面", "en": "satin", "desc": "缎面面料"},
                    {"zh": "网纱", "en": "mesh sheer fabric", "desc": "网纱面料"},
                    {"zh": "羊绒", "en": "cashmere", "desc": "羊绒面料"},
                    {"zh": "羊毛", "en": "wool", "desc": "羊毛面料"},
                    {"zh": "粗花呢", "en": "tweed", "desc": "粗花呢面料"},
                    {"zh": "灯芯绒", "en": "corduroy", "desc": "灯芯绒面料"},
                    {"zh": "欧根纱", "en": "organza", "desc": "欧根纱面料"},
                    {"zh": "绉纱", "en": "crepe", "desc": "绉纱面料"},
                    {"zh": "提花", "en": "jacquard", "desc": "提花面料"},
                    {"zh": "人造革", "en": "faux leather", "desc": "人造革面料"},
                    {"zh": "金属面料", "en": "metallic fabric", "desc": "金属面料"},
                    {"zh": "棉麻混纺", "en": "cotton-linen blend", "desc": "棉麻混纺面料"},
                    {"zh": "冰丝", "en": "ice silk fabric", "desc": "冰丝面料"},
                    {"zh": "莫代尔", "en": "modal fabric", "desc": "莫代尔面料"},
                    {"zh": "真丝缎", "en": "silk satin", "desc": "真丝缎面料"},
                ],
            },
            {
                "name": "结构细节",
                "key": "structural_detail",
                "multi": True,
                "options": [
                    {"zh": "荷叶边", "en": "ruffles", "desc": "荷叶边装饰"},
                    {"zh": "褶皱", "en": "pleats", "desc": "褶皱设计"},
                    {"zh": "抽褶", "en": "shirring", "desc": "抽褶设计"},
                    {"zh": "均匀抽褶", "en": "even gathering", "desc": "均匀抽褶设计"},
                    {"zh": "镂空", "en": "cutout", "desc": "镂空设计"},
                    {"zh": "拼接", "en": "color block patchwork", "desc": "拼接设计"},
                    {"zh": "刺绣", "en": "embroidery", "desc": "刺绣装饰"},
                    {"zh": "亮片", "en": "sequins", "desc": "亮片装饰"},
                    {"zh": "珠饰", "en": "beading", "desc": "珠饰装饰"},
                    {"zh": "系带", "en": "lace-up tie", "desc": "系带设计"},
                    {"zh": "抽绳", "en": "drawstring", "desc": "抽绳设计"},
                    {"zh": "蝴蝶结", "en": "bow", "desc": "蝴蝶结装饰"},
                    {"zh": "肩垫", "en": "shoulder pads", "desc": "肩垫设计"},
                    {"zh": "不对称设计", "en": "asymmetric design", "desc": "不对称设计"},
                    {"zh": "层叠", "en": "tiered layered", "desc": "层叠设计"},
                    {"zh": "露背", "en": "open back", "desc": "露背设计"},
                    {"zh": "绑带", "en": "strappy", "desc": "绑带设计"},
                    {"zh": "荷叶边领口", "en": "ruffle neckline", "desc": "荷叶边领口"},
                    {"zh": "领口抽褶", "en": "gathered neckline", "desc": "领口抽褶设计"},
                    {"zh": "压褶", "en": "press pleats", "desc": "压褶设计"},
                    {"zh": "绗缝", "en": "quilted", "desc": "绗缝设计"},
                    {"zh": "扭结", "en": "twist knot", "desc": "扭结设计"},
                    {"zh": "垂坠堆叠", "en": "draping", "desc": "垂坠堆叠设计"},
                    {"zh": "泡泡肌理", "en": "smocking", "desc": "泡泡肌理设计"},
                    {"zh": "公主线剪裁", "en": "princess seam", "desc": "公主线剪裁"},
                    {"zh": "开叉设计", "en": "split design", "desc": "开叉设计"},
                    {"zh": "毛边", "en": "raw edge", "desc": "毛边设计"},
                    {"zh": "珍珠装饰", "en": "pearl embellishment", "desc": "珍珠装饰"},
                    {"zh": "流苏", "en": "fringe tassels", "desc": "流苏装饰"},
                    {"zh": "镂空编织", "en": "crochet openwork", "desc": "镂空编织设计"},
                    {"zh": "胸前褶皱", "en": "bust pleats", "desc": "胸前褶皱设计"},
                    {"zh": "腰部收褶", "en": "waist gathering", "desc": "腰部收褶设计"},
                    {"zh": "交叉绑带", "en": "cross strappy", "desc": "交叉绑带设计"},
                    {"zh": "下摆不规则", "en": "asymmetric hem", "desc": "下摆不规则设计"},
                    {"zh": "袖口开叉", "en": "split cuffs", "desc": "袖口开叉设计"},
                    {"zh": "前短后长", "en": "high-low hem", "desc": "前短后长设计"},
                    {"zh": "褶皱收腰", "en": "shirred waist", "desc": "褶皱收腰设计"},
                    {"zh": "花边装饰", "en": "lace trim", "desc": "花边装饰"},
                    {"zh": "蝴蝶结系带", "en": "bow tie", "desc": "蝴蝶结系带"},
                    {"zh": "胸部收束", "en": "underbust cinch", "desc": "胸部收束设计"},
                    {"zh": "高腰线收束", "en": "empire waist", "desc": "高腰线收束设计"},
                    {"zh": "松紧收腰", "en": "elastic waist", "desc": "松紧收腰设计"},
                    {"zh": "腰带收腰", "en": "belt cinched", "desc": "腰带收腰设计"},
                ],
            },
        ],
    },
    {
        "name": "外套",
        "icon": "🧥",
        "modules": [
            {
                "name": "款式",
                "key": "outerwear_type",
                "multi": False,
                "options": [
                    {"zh": "西装外套", "en": "blazer", "desc": "西装外套"},
                    {"zh": "风衣", "en": "trench coat", "desc": "风衣"},
                    {"zh": "大衣", "en": "overcoat", "desc": "大衣"},
                    {"zh": "牛仔夹克", "en": "denim jacket", "desc": "牛仔夹克"},
                    {"zh": "皮夹克", "en": "leather jacket", "desc": "皮夹克"},
                    {"zh": "飞行员夹克", "en": "bomber jacket", "desc": "飞行员夹克"},
                    {"zh": "棒球服", "en": "baseball jacket", "desc": "棒球服"},
                    {"zh": "开衫外套", "en": "cardigan", "desc": "开衫外套"},
                    {"zh": "马甲", "en": "vest", "desc": "马甲外套"},
                    {"zh": "斗篷", "en": "cape", "desc": "斗篷"},
                    {"zh": "羽绒服", "en": "puffer jacket", "desc": "羽绒服"},
                    {"zh": "机车夹克", "en": "moto jacket", "desc": "机车夹克"},
                    {"zh": "粗花呢外套", "en": "tweed jacket", "desc": "粗花呢外套"},
                    {"zh": "工装夹克", "en": "workwear jacket", "desc": "工装夹克"},
                    {"zh": "冲锋衣", "en": "shell jacket", "desc": "冲锋衣"},
                    {"zh": "针织开衫", "en": "knit cardigan", "desc": "针织开衫"},
                    {"zh": "长款马甲", "en": "long vest", "desc": "长款马甲"},
                    {"zh": "披肩", "en": "shawl", "desc": "披肩"},
                    {"zh": "短外套", "en": "cropped jacket", "desc": "短外套"},
                    {"zh": "长款风衣", "en": "long trench coat", "desc": "长款风衣"},
                    {"zh": "双面呢大衣", "en": "double-faced wool coat", "desc": "双面呢大衣"},
                    {"zh": "毛皮外套", "en": "fur coat", "desc": "毛皮外套"},
                    {"zh": "羽绒马甲", "en": "puffer vest", "desc": "羽绒马甲"},
                ],
            },
            {
                "name": "外套廓形",
                "key": "outerwear_silhouette",
                "multi": False,
                "options": [
                    {"zh": "修身", "en": "fitted", "desc": "修身廓形"},
                    {"zh": "直筒", "en": "straight cut", "desc": "直筒廓形"},
                    {"zh": "茧型", "en": "cocoon shape", "desc": "茧型廓形"},
                    {"zh": "oversized", "en": "oversized", "desc": "oversized廓形"},
                    {"zh": "A字", "en": "a-line", "desc": "A字廓形"},
                    {"zh": "收腰", "en": "cinched waist", "desc": "收腰廓形"},
                    {"zh": "宽松", "en": "relaxed fit", "desc": "宽松廓形"},
                    {"zh": "短款", "en": "cropped", "desc": "短款廓形"},
                    {"zh": "中长款", "en": "mid-length", "desc": "中长款廓形"},
                    {"zh": "长款", "en": "long", "desc": "长款廓形"},
                    {"zh": "超长长款", "en": "maxi length", "desc": "超长长款廓形"},
                ],
            },
            {
                "name": "外套细节",
                "key": "outerwear_detail",
                "multi": True,
                "options": [
                    {"zh": "双排扣", "en": "double-breasted", "desc": "双排扣设计"},
                    {"zh": "单排扣", "en": "single-breasted", "desc": "单排扣设计"},
                    {"zh": "系带腰带", "en": "belt tie", "desc": "系带腰带"},
                    {"zh": "肩章", "en": "epaulettes", "desc": "肩章装饰"},
                    {"zh": "大翻领", "en": "wide lapel", "desc": "大翻领设计"},
                    {"zh": "无领", "en": "collarless", "desc": "无领设计"},
                    {"zh": "连帽", "en": "hooded", "desc": "连帽设计"},
                    {"zh": "拉链", "en": "zip front", "desc": "拉链设计"},
                    {"zh": "牛角扣", "en": "toggle buttons", "desc": "牛角扣设计"},
                    {"zh": "绗缝", "en": "quilted", "desc": "绗缝设计"},
                    {"zh": "拼接设计", "en": "patchwork", "desc": "拼接设计"},
                    {"zh": "毛领", "en": "fur collar", "desc": "毛领设计"},
                    {"zh": "口袋装饰", "en": "pocket detail", "desc": "口袋装饰"},
                    {"zh": "袖口装饰", "en": "cuff detail", "desc": "袖口装饰"},
                ],
            },
        ],
    },
    {
        "name": "下装",
        "icon": "👖",
        "modules": [
            {
                "name": "裤装款式",
                "key": "pants_type",
                "multi": False,
                "options": [
                    {"zh": "牛仔裤", "en": "jeans", "desc": "牛仔裤"},
                    {"zh": "阔腿裤", "en": "wide-leg pants", "desc": "阔腿裤"},
                    {"zh": "直筒裤", "en": "straight-leg pants", "desc": "直筒裤"},
                    {"zh": "紧身裤", "en": "skinny pants", "desc": "紧身裤"},
                    {"zh": "喇叭裤", "en": "flare pants", "desc": "喇叭裤"},
                    {"zh": "工装裤", "en": "cargo pants", "desc": "工装裤"},
                    {"zh": "运动裤", "en": "joggers", "desc": "运动裤"},
                    {"zh": "西装裤", "en": "tailored trousers", "desc": "西装裤"},
                    {"zh": "打底裤", "en": "leggings", "desc": "打底裤"},
                    {"zh": "热裤", "en": "hot pants", "desc": "热裤"},
                    {"zh": "百慕大短裤", "en": "bermuda shorts", "desc": "百慕大短裤"},
                    {"zh": "高腰短裤", "en": "high-waist shorts", "desc": "高腰短裤"},
                    {"zh": "骑行裤", "en": "cycling shorts", "desc": "骑行裤"},
                    {"zh": "瑜伽裤", "en": "yoga pants", "desc": "瑜伽裤"},
                    {"zh": "哈伦裤", "en": "harem pants", "desc": "哈伦裤"},
                    {"zh": "纸袋裤", "en": "paper bag pants", "desc": "纸袋裤"},
                    {"zh": "烟管裤", "en": "cigarette pants", "desc": "烟管裤"},
                ],
            },
            {
                "name": "裙装款式",
                "key": "skirt_type",
                "multi": False,
                "options": [
                    {"zh": "迷你裙", "en": "mini skirt", "desc": "迷你裙"},
                    {"zh": "A字裙", "en": "a-line skirt", "desc": "A字裙"},
                    {"zh": "包臀裙", "en": "pencil skirt", "desc": "包臀裙"},
                    {"zh": "百褶裙", "en": "pleated skirt", "desc": "百褶裙"},
                    {"zh": "伞裙", "en": "circle skirt", "desc": "伞裙"},
                    {"zh": "中长裙", "en": "midi skirt", "desc": "中长裙"},
                    {"zh": "长裙", "en": "maxi skirt", "desc": "长裙"},
                    {"zh": "纱裙", "en": "tulle skirt", "desc": "纱裙"},
                    {"zh": "牛仔裙", "en": "denim skirt", "desc": "牛仔裙"},
                    {"zh": "鱼尾裙", "en": "mermaid skirt", "desc": "鱼尾裙"},
                    {"zh": "不规则裙", "en": "asymmetric skirt", "desc": "不规则裙"},
                    {"zh": "紧身短裙", "en": "tight mini skirt", "desc": "紧身短裙"},
                    {"zh": "高腰裙", "en": "high-waist skirt", "desc": "高腰裙"},
                    {"zh": "格子裙", "en": "plaid skirt", "desc": "格子裙"},
                    {"zh": "蕾丝裙", "en": "lace skirt", "desc": "蕾丝裙"},
                    {"zh": "针织裙", "en": "knit skirt", "desc": "针织裙"},
                    {"zh": "缎面裙", "en": "satin skirt", "desc": "缎面裙"},
                    {"zh": "层叠裙", "en": "tiered skirt", "desc": "层叠裙"},
                ],
            },
            {
                "name": "腰型",
                "key": "waist_type",
                "multi": False,
                "options": [
                    {"zh": "高腰", "en": "high-waist", "desc": "高腰设计"},
                    {"zh": "中腰", "en": "mid-rise", "desc": "中腰设计"},
                    {"zh": "低腰", "en": "low-rise", "desc": "低腰设计"},
                    {"zh": "超高腰", "en": "super high-waist", "desc": "超高腰设计"},
                    {"zh": "松紧腰", "en": "elastic waist", "desc": "松紧腰设计"},
                    {"zh": "系带腰", "en": "tie waist", "desc": "系带腰设计"},
                    {"zh": "纸袋腰", "en": "paper bag waist", "desc": "纸袋腰设计"},
                ],
            },
            {
                "name": "下摆/细节",
                "key": "bottom_detail",
                "multi": True,
                "options": [
                    {"zh": "毛边", "en": "raw hem", "desc": "毛边设计"},
                    {"zh": "破洞", "en": "ripped distressed", "desc": "破洞设计"},
                    {"zh": "开叉", "en": "slits", "desc": "开叉设计"},
                    {"zh": "褶皱", "en": "pleats", "desc": "褶皱设计"},
                    {"zh": "侧条纹", "en": "side stripe", "desc": "侧条纹设计"},
                    {"zh": "不规则下摆", "en": "asymmetric hem", "desc": "不规则下摆设计"},
                    {"zh": "蕾丝边", "en": "lace trim hem", "desc": "蕾丝边设计"},
                    {"zh": "荷叶边下摆", "en": "ruffle hem", "desc": "荷叶边下摆设计"},
                    {"zh": "拼接设计", "en": "patchwork", "desc": "拼接设计"},
                    {"zh": "刺绣细节", "en": "embroidered detail", "desc": "刺绣细节"},
                    {"zh": "口袋装饰", "en": "pocket detail", "desc": "口袋装饰"},
                    {"zh": "缝线装饰", "en": "stitching detail", "desc": "缝线装饰"},
                    {"zh": "系带细节", "en": "tie detail", "desc": "系带细节"},
                ],
            },
            {
                "name": "长度",
                "key": "bottom_length",
                "multi": False,
                "options": [
                    {"zh": "超短", "en": "ultra short", "desc": "超短长度"},
                    {"zh": "膝上", "en": "above knee", "desc": "膝上长度"},
                    {"zh": "及膝", "en": "knee length", "desc": "及膝长度"},
                    {"zh": "小腿中", "en": "calf length", "desc": "小腿中长度"},
                    {"zh": "九分", "en": "ankle length", "desc": "九分长度"},
                    {"zh": "及地", "en": "floor length", "desc": "及地长度"},
                    {"zh": "拖地", "en": "puddle length", "desc": "拖地长度"},
                ],
            },
        ],
    },
    {
        "name": "连衣裙",
        "icon": "👗",
        "modules": [
            {
                "name": "连衣裙款式",
                "key": "dress_type",
                "multi": False,
                "options": [
                    {"zh": "吊带裙", "en": "slip dress", "desc": "吊带裙"},
                    {"zh": "衬衫裙", "en": "shirt dress", "desc": "衬衫裙"},
                    {"zh": "茶歇裙", "en": "tea dress", "desc": "茶歇裙"},
                    {"zh": "裹身裙", "en": "wrap dress", "desc": "裹身裙"},
                    {"zh": "娃娃裙", "en": "babydoll dress", "desc": "娃娃裙"},
                    {"zh": "公主裙", "en": "princess dress", "desc": "公主裙"},
                    {"zh": "鱼尾裙", "en": "mermaid dress", "desc": "鱼尾连衣裙"},
                    {"zh": "A字连衣裙", "en": "a-line dress", "desc": "A字连衣裙"},
                    {"zh": "直筒连衣裙", "en": "sheath dress", "desc": "直筒连衣裙"},
                    {"zh": "蛋糕裙", "en": "tiered dress", "desc": "蛋糕裙"},
                    {"zh": "抹胸长裙", "en": "strapless gown", "desc": "抹胸长裙"},
                    {"zh": "露背连衣裙", "en": "open back dress", "desc": "露背连衣裙"},
                    {"zh": "衬衫式连衣裙", "en": "shirtdress", "desc": "衬衫式连衣裙"},
                    {"zh": "针织连衣裙", "en": "knit dress", "desc": "针织连衣裙"},
                    {"zh": "蕾丝连衣裙", "en": "lace dress", "desc": "蕾丝连衣裙"},
                    {"zh": "印花连衣裙", "en": "print dress", "desc": "印花连衣裙"},
                    {"zh": "雪纺连衣裙", "en": "chiffon dress", "desc": "雪纺连衣裙"},
                    {"zh": "缎面礼服", "en": "satin gown", "desc": "缎面礼服"},
                    {"zh": "不规则连衣裙", "en": "asymmetric dress", "desc": "不规则连衣裙"},
                    {"zh": "露肩连衣裙", "en": "off-shoulder dress", "desc": "露肩连衣裙"},
                    {"zh": "高领连衣裙", "en": "turtleneck dress", "desc": "高领连衣裙"},
                    {"zh": "碎花连衣裙", "en": "floral dress", "desc": "碎花连衣裙"},
                    {"zh": "紧身连衣裙", "en": "bodycon dress", "desc": "紧身连衣裙"},
                    {"zh": "宽松连衣裙", "en": "loose fit dress", "desc": "宽松连衣裙"},
                    {"zh": "背带连衣裙", "en": "overall dress", "desc": "背带连衣裙"},
                    {"zh": "泡泡袖连衣裙", "en": "puff sleeve dress", "desc": "泡泡袖连衣裙"},
                ],
            },
            {
                "name": "连衣裙长度",
                "key": "dress_length",
                "multi": False,
                "options": [
                    {"zh": "迷你", "en": "mini dress", "desc": "迷你长度"},
                    {"zh": "膝上", "en": "above knee", "desc": "膝上长度"},
                    {"zh": "及膝", "en": "knee length", "desc": "及膝长度"},
                    {"zh": "midi", "en": "midi dress", "desc": "midi长度"},
                    {"zh": "及踝", "en": "maxi dress", "desc": "及踝长度"},
                    {"zh": "拖地", "en": "floor-length gown", "desc": "拖地长度"},
                    {"zh": "前短后长", "en": "high-low", "desc": "前短后长设计"},
                ],
            },
            {
                "name": "连衣裙细节",
                "key": "dress_detail",
                "multi": True,
                "options": [
                    {"zh": "系带收腰", "en": "tie waist", "desc": "系带收腰设计"},
                    {"zh": "松紧腰", "en": "elastic waist", "desc": "松紧腰设计"},
                    {"zh": "层叠裙摆", "en": "tiered skirt", "desc": "层叠裙摆设计"},
                    {"zh": "荷叶边装饰", "en": "ruffle detail", "desc": "荷叶边装饰"},
                    {"zh": "镂空设计", "en": "cutout detail", "desc": "镂空设计"},
                    {"zh": "蕾丝拼接", "en": "lace panel", "desc": "蕾丝拼接设计"},
                    {"zh": "开叉设计", "en": "high slit", "desc": "开叉设计"},
                    {"zh": "蝴蝶结装饰", "en": "bow detail", "desc": "蝴蝶结装饰"},
                    {"zh": "珍珠装饰", "en": "pearl detail", "desc": "珍珠装饰"},
                    {"zh": "刺绣", "en": "embroidery", "desc": "刺绣装饰"},
                    {"zh": "亮片点缀", "en": "sequin accent", "desc": "亮片点缀"},
                    {"zh": "不对称设计", "en": "asymmetric", "desc": "不对称设计"},
                    {"zh": "公主线剪裁", "en": "princess seam", "desc": "公主线剪裁"},
                    {"zh": "后背羽翼", "en": "wing back detail", "desc": "后背羽翼设计"},
                    {"zh": "蓬蓬裙摆", "en": "poofy skirt", "desc": "蓬蓬裙摆设计"},
                    {"zh": "拖尾", "en": "train", "desc": "拖尾设计"},
                ],
            },
        ],
    },
    {
        "name": "鞋履",
        "icon": "👠",
        "modules": [
            {
                "name": "高跟鞋",
                "key": "heels_type",
                "multi": False,
                "options": [
                    {"zh": "细跟高跟鞋", "en": "stiletto heels", "desc": "细跟高跟鞋"},
                    {"zh": "粗跟高跟鞋", "en": "block heels", "desc": "粗跟高跟鞋"},
                    {"zh": "猫跟鞋", "en": "kitten heels", "desc": "猫跟鞋"},
                    {"zh": "方跟鞋", "en": "square heels", "desc": "方跟鞋"},
                    {"zh": "坡跟鞋", "en": "wedge heels", "desc": "坡跟鞋"},
                    {"zh": "细跟凉鞋", "en": "stiletto sandals", "desc": "细跟凉鞋"},
                    {"zh": "尖头高跟鞋", "en": "pointed pumps", "desc": "尖头高跟鞋"},
                ],
            },
            {
                "name": "平底鞋",
                "key": "flats_type",
                "multi": False,
                "options": [
                    {"zh": "芭蕾鞋", "en": "ballet flats", "desc": "芭蕾鞋"},
                    {"zh": "乐福鞋", "en": "loafers", "desc": "乐福鞋"},
                    {"zh": "牛津鞋", "en": "oxford shoes", "desc": "牛津鞋"},
                    {"zh": "玛丽珍鞋", "en": "mary janes", "desc": "玛丽珍鞋"},
                    {"zh": "尖头平底鞋", "en": "pointed flats", "desc": "尖头平底鞋"},
                    {"zh": "编织平底鞋", "en": "woven flats", "desc": "编织平底鞋"},
                    {"zh": "穆勒鞋", "en": "mule flats", "desc": "穆勒平底鞋"},
                ],
            },
            {
                "name": "运动鞋",
                "key": "sneakers_type",
                "multi": False,
                "options": [
                    {"zh": "老爹鞋", "en": "chunky sneakers", "desc": "老爹鞋"},
                    {"zh": "板鞋", "en": "platform sneakers", "desc": "板鞋"},
                    {"zh": "帆布鞋", "en": "canvas shoes", "desc": "帆布鞋"},
                    {"zh": "跑鞋", "en": "running shoes", "desc": "跑鞋"},
                    {"zh": "高帮运动鞋", "en": "high-top sneakers", "desc": "高帮运动鞋"},
                    {"zh": "厚底运动鞋", "en": "platform sneakers", "desc": "厚底运动鞋"},
                    {"zh": "复古运动鞋", "en": "retro sneakers", "desc": "复古运动鞋"},
                    {"zh": "德训鞋", "en": "german army trainer sneakers", "desc": "德训鞋"},
                ],
            },
            {
                "name": "靴子",
                "key": "boots_type",
                "multi": False,
                "options": [
                    {"zh": "马丁靴", "en": "combat boots", "desc": "马丁靴"},
                    {"zh": "切尔西靴", "en": "chelsea boots", "desc": "切尔西靴"},
                    {"zh": "过膝靴", "en": "over-the-knee boots", "desc": "过膝靴"},
                    {"zh": "骑士靴", "en": "knee-high boots", "desc": "骑士靴"},
                    {"zh": "及踝靴", "en": "ankle boots", "desc": "及踝靴"},
                    {"zh": "雪地靴", "en": "snow boots", "desc": "雪地靴"},
                    {"zh": "西部靴", "en": "cowboy boots", "desc": "西部靴"},
                    {"zh": "袜靴", "en": "sock boots", "desc": "袜靴"},
                    {"zh": "长筒靴", "en": "tall boots", "desc": "长筒靴"},
                    {"zh": "方头靴", "en": "square toe boots", "desc": "方头靴"},
                    {"zh": "尖头靴", "en": "pointed boots", "desc": "尖头靴"},
                ],
            },
            {
                "name": "凉鞋",
                "key": "sandals_type",
                "multi": False,
                "options": [
                    {"zh": "一字带凉鞋", "en": "strappy sandals", "desc": "一字带凉鞋"},
                    {"zh": "罗马凉鞋", "en": "gladiator sandals", "desc": "罗马凉鞋"},
                    {"zh": "厚底凉鞋", "en": "platform sandals", "desc": "厚底凉鞋"},
                    {"zh": "人字拖", "en": "flip flops", "desc": "人字拖"},
                    {"zh": "编织凉鞋", "en": "woven sandals", "desc": "编织凉鞋"},
                    {"zh": "绑带凉鞋", "en": "lace-up sandals", "desc": "绑带凉鞋"},
                    {"zh": "运动凉鞋", "en": "sport sandals", "desc": "运动凉鞋"},
                ],
            },
            {
                "name": "其他鞋款",
                "key": "other_shoes",
                "multi": False,
                "options": [
                    {"zh": "穆勒鞋", "en": "mules", "desc": "穆勒鞋"},
                    {"zh": "尖头鞋", "en": "pointed shoes", "desc": "尖头鞋"},
                    {"zh": "方头鞋", "en": "square toe shoes", "desc": "方头鞋"},
                    {"zh": "德比鞋", "en": "derby shoes", "desc": "德比鞋"},
                    {"zh": "草编鞋", "en": "espadrilles", "desc": "草编鞋"},
                    {"zh": "乐福鞋", "en": "platform loafers", "desc": "厚底乐福鞋"},
                    {"zh": "豆豆鞋", "en": "driving shoes", "desc": "豆豆鞋"},
                    {"zh": "松糕鞋", "en": "platform shoes", "desc": "松糕鞋"},
                ],
            },
            {
                "name": "鞋跟高度",
                "key": "heel_height",
                "multi": False,
                "options": [
                    {"zh": "平底", "en": "flat", "desc": "平底"},
                    {"zh": "低跟", "en": "low heel 1-3cm", "desc": "低跟1-3cm"},
                    {"zh": "中跟", "en": "mid heel 3-5cm", "desc": "中跟3-5cm"},
                    {"zh": "高跟", "en": "high heel 5-8cm", "desc": "高跟5-8cm"},
                    {"zh": "超高跟", "en": "very high heel 8cm+", "desc": "超高跟8cm+"},
                    {"zh": "坡跟", "en": "wedge", "desc": "坡跟"},
                ],
            },
            {
                "name": "鞋头形状",
                "key": "toe_shape",
                "multi": False,
                "options": [
                    {"zh": "尖头", "en": "pointed toe", "desc": "尖头设计"},
                    {"zh": "方头", "en": "square toe", "desc": "方头设计"},
                    {"zh": "圆头", "en": "round toe", "desc": "圆头设计"},
                    {"zh": "杏仁头", "en": "almond toe", "desc": "杏仁头设计"},
                    {"zh": "露趾", "en": "open toe", "desc": "露趾设计"},
                    {"zh": "猫趾", "en": "cat toe", "desc": "猫趾设计"},
                ],
            },
        ],
    },
    {
        "name": "包袋",
        "icon": "👜",
        "modules": [
            {
                "name": "包袋款式",
                "key": "bag_type",
                "multi": False,
                "options": [
                    {"zh": "托特包", "en": "tote bag", "desc": "托特包"},
                    {"zh": "单肩包", "en": "shoulder bag", "desc": "单肩包"},
                    {"zh": "斜挎包", "en": "crossbody bag", "desc": "斜挎包"},
                    {"zh": "手提包", "en": "handbag", "desc": "手提包"},
                    {"zh": "双肩包", "en": "backpack", "desc": "双肩包"},
                    {"zh": "腰包", "en": "fanny pack", "desc": "腰包"},
                    {"zh": "胸包", "en": "chest bag", "desc": "胸包"},
                    {"zh": "信封包", "en": "envelope bag", "desc": "信封包"},
                    {"zh": "水桶包", "en": "bucket bag", "desc": "水桶包"},
                    {"zh": "菜篮子包", "en": "market bag", "desc": "菜篮子包"},
                    {"zh": "贝壳包", "en": "shell bag", "desc": "贝壳包"},
                    {"zh": "链条包", "en": "chain bag", "desc": "链条包"},
                    {"zh": "Hobo包", "en": "hobo bag", "desc": "Hobo包"},
                    {"zh": "手拿包", "en": "clutch", "desc": "手拿包"},
                    {"zh": "迷你包", "en": "mini bag", "desc": "迷你包"},
                    {"zh": "大号包", "en": "oversized bag", "desc": "大号包"},
                    {"zh": "半月包", "en": "half-moon bag", "desc": "半月包"},
                    {"zh": "法棍包", "en": "baguette bag", "desc": "法棍包"},
                    {"zh": "云朵包", "en": "cloud bag", "desc": "云朵包"},
                    {"zh": "编织包", "en": "woven bag", "desc": "编织包"},
                    {"zh": "复古口金包", "en": "vintage kiss-lock bag", "desc": "复古口金包"},
                    {"zh": "果冻包", "en": "jelly bag", "desc": "果冻包"},
                    {"zh": "草编包", "en": "straw bag", "desc": "草编包"},
                    {"zh": "珍珠包", "en": "pearl bag", "desc": "珍珠包"},
                ],
            },
        ],
    },
    {
        "name": "配饰",
        "icon": "💎",
        "modules": [
            {
                "name": "项链",
                "key": "necklace",
                "multi": True,
                "options": [
                    {"zh": "锁骨链", "en": "collarbone necklace", "desc": "锁骨链"},
                    {"zh": "长项链", "en": "long necklace", "desc": "长项链"},
                    {"zh": "贴颈链", "en": "choker necklace", "desc": "贴颈项链"},
                    {"zh": "珍珠项链", "en": "pearl necklace", "desc": "珍珠项链"},
                    {"zh": "吊坠项链", "en": "pendant necklace", "desc": "吊坠项链"},
                    {"zh": "叠戴项链", "en": "layered necklaces", "desc": "叠戴项链"},
                    {"zh": "链条项链", "en": "chain necklace", "desc": "链条项链"},
                    {"zh": "水钻项链", "en": "rhinestone necklace", "desc": "水钻项链"},
                    {"zh": "身体链", "en": "body chain", "desc": "身体链"},
                ],
            },
            {
                "name": "耳饰",
                "key": "earrings",
                "multi": True,
                "options": [
                    {"zh": "耳钉", "en": "stud earrings", "desc": "耳钉"},
                    {"zh": "耳线", "en": "thread earrings", "desc": "耳线"},
                    {"zh": "圆环耳环", "en": "hoop earrings", "desc": "圆环耳环"},
                    {"zh": "耳骨夹", "en": "ear cuff", "desc": "耳骨夹"},
                    {"zh": "流苏耳环", "en": "tassel earrings", "desc": "流苏耳环"},
                    {"zh": "珍珠耳环", "en": "pearl earrings", "desc": "珍珠耳环"},
                    {"zh": "水滴耳环", "en": "teardrop earrings", "desc": "水滴耳环"},
                    {"zh": "几何耳环", "en": "geometric earrings", "desc": "几何耳环"},
                    {"zh": "羽毛耳环", "en": "feather earrings", "desc": "羽毛耳环"},
                ],
            },
            {
                "name": "手部饰品",
                "key": "hand_accessories",
                "multi": True,
                "options": [
                    {"zh": "手链", "en": "bracelet", "desc": "手链"},
                    {"zh": "手镯", "en": "bangle", "desc": "手镯"},
                    {"zh": "戒指", "en": "ring", "desc": "戒指"},
                    {"zh": "叠戴戒指", "en": "stacked rings", "desc": "叠戴戒指"},
                    {"zh": "手表", "en": "watch", "desc": "手表"},
                    {"zh": "手镯叠戴", "en": "layered bangles", "desc": "手镯叠戴"},
                    {"zh": "串珠手链", "en": "beaded bracelet", "desc": "串珠手链"},
                    {"zh": "链条手链", "en": "chain bracelet", "desc": "链条手链"},
                ],
            },
            {
                "name": "头饰",
                "key": "head_accessories",
                "multi": True,
                "options": [
                    {"zh": "贝雷帽", "en": "beret", "desc": "贝雷帽"},
                    {"zh": "渔夫帽", "en": "bucket hat", "desc": "渔夫帽"},
                    {"zh": "棒球帽", "en": "baseball cap", "desc": "棒球帽"},
                    {"zh": "宽檐帽", "en": "wide-brim hat", "desc": "宽檐帽"},
                    {"zh": "发箍", "en": "headband", "desc": "发箍"},
                    {"zh": "发带", "en": "hair band", "desc": "发带"},
                    {"zh": "丝巾绑发", "en": "silk scarf hair tie", "desc": "丝巾绑发"},
                    {"zh": "大蝴蝶结发夹", "en": "big bow hair clip", "desc": "大蝴蝶结发夹"},
                    {"zh": "珍珠发夹", "en": "pearl hair clip", "desc": "珍珠发夹"},
                    {"zh": "鲨鱼夹", "en": "claw clip", "desc": "鲨鱼夹"},
                    {"zh": "头巾", "en": "headscarf", "desc": "头巾"},
                    {"zh": "小礼帽", "en": "fascinator", "desc": "小礼帽"},
                    {"zh": "花环发饰", "en": "flower crown", "desc": "花环发饰"},
                    {"zh": "水钻发夹", "en": "rhinestone hair clip", "desc": "水钻发夹"},
                ],
            },
            {
                "name": "腰饰",
                "key": "waist_accessories",
                "multi": True,
                "options": [
                    {"zh": "细腰带", "en": "thin belt", "desc": "细腰带"},
                    {"zh": "宽腰封", "en": "wide waist cincher", "desc": "宽腰封"},
                    {"zh": "链条腰带", "en": "chain belt", "desc": "链条腰带"},
                    {"zh": "编织腰带", "en": "woven belt", "desc": "编织腰带"},
                    {"zh": "丝带腰带", "en": "ribbon belt", "desc": "丝带腰带"},
                    {"zh": "珍珠腰链", "en": "pearl waist chain", "desc": "珍珠腰链"},
                    {"zh": "装饰腰带", "en": "decorative belt", "desc": "装饰腰带"},
                ],
            },
            {
                "name": "面部配饰",
                "key": "face_accessories",
                "multi": True,
                "options": [
                    {"zh": "墨镜", "en": "sunglasses", "desc": "墨镜"},
                    {"zh": "猫眼墨镜", "en": "cat-eye sunglasses", "desc": "猫眼墨镜"},
                    {"zh": "圆框墨镜", "en": "round sunglasses", "desc": "圆框墨镜"},
                    {"zh": "方框墨镜", "en": "square sunglasses", "desc": "方框墨镜"},
                    {"zh": "飞行员墨镜", "en": "aviator sunglasses", "desc": "飞行员墨镜"},
                    {"zh": "装饰口罩", "en": "decorative mask", "desc": "装饰口罩"},
                    {"zh": "面纱", "en": "veil", "desc": "面纱"},
                    {"zh": "单片眼镜", "en": "monocle", "desc": "单片眼镜"},
                ],
            },
            {
                "name": "其他配饰",
                "key": "other_accessories",
                "multi": True,
                "options": [
                    {"zh": "丝巾", "en": "silk scarf", "desc": "丝巾"},
                    {"zh": "围巾", "en": "scarf", "desc": "围巾"},
                    {"zh": "披肩", "en": "shawl", "desc": "披肩"},
                    {"zh": "领带", "en": "tie", "desc": "领带"},
                    {"zh": "领结", "en": "bow tie", "desc": "领结"},
                    {"zh": "手套", "en": "gloves", "desc": "手套"},
                    {"zh": "蕾丝手套", "en": "lace gloves", "desc": "蕾丝手套"},
                    {"zh": "皮手套", "en": "leather gloves", "desc": "皮手套"},
                    {"zh": "胸针", "en": "brooch", "desc": "胸针"},
                    {"zh": "臂环", "en": "arm band", "desc": "臂环"},
                    {"zh": "脚踝链", "en": "anklet", "desc": "脚踝链"},
                    {"zh": "项圈", "en": "collar", "desc": "项圈"},
                    {"zh": "折扇", "en": "folding fan", "desc": "折扇"},
                    {"zh": "手机链", "en": "phone charm", "desc": "手机链"},
                ],
            },
        ],
    },
    {
        "name": "色彩",
        "icon": "🌈",
        "modules": [
            {
                "name": "基础色",
                "key": "color_basic",
                "multi": True,
                "options": [
                    {"zh": "白色", "en": "white", "desc": "白色"},
                    {"zh": "黑色", "en": "black", "desc": "黑色"},
                    {"zh": "米色", "en": "beige", "desc": "米色"},
                    {"zh": "驼色", "en": "camel", "desc": "驼色"},
                    {"zh": "灰色", "en": "gray", "desc": "灰色"},
                    {"zh": "浅灰", "en": "light gray", "desc": "浅灰色"},
                    {"zh": "深灰", "en": "dark gray", "desc": "深灰色"},
                    {"zh": "正红", "en": "red", "desc": "正红色"},
                    {"zh": "酒红", "en": "burgundy", "desc": "酒红色"},
                    {"zh": "粉红", "en": "pink", "desc": "粉红色"},
                    {"zh": "橙色", "en": "orange", "desc": "橙色"},
                    {"zh": "黄色", "en": "yellow", "desc": "黄色"},
                    {"zh": "绿色", "en": "green", "desc": "绿色"},
                    {"zh": "蓝色", "en": "blue", "desc": "蓝色"},
                    {"zh": "藏青", "en": "navy", "desc": "藏青色"},
                    {"zh": "紫色", "en": "purple", "desc": "紫色"},
                    {"zh": "棕色", "en": "brown", "desc": "棕色"},
                ],
            },
            {
                "name": "流行色",
                "key": "color_trend",
                "multi": True,
                "options": [
                    {"zh": "莫兰迪粉", "en": "morandi pink", "desc": "莫兰迪粉"},
                    {"zh": "莫兰迪蓝", "en": "morandi blue", "desc": "莫兰迪蓝"},
                    {"zh": "莫兰迪绿", "en": "morandi green", "desc": "莫兰迪绿"},
                    {"zh": "烟紫", "en": "dusty purple", "desc": "烟紫色"},
                    {"zh": "灰蓝", "en": "gray blue", "desc": "灰蓝色"},
                    {"zh": "雾霾蓝", "en": "haze blue", "desc": "雾霾蓝"},
                    {"zh": "薄荷绿", "en": "mint green", "desc": "薄荷绿"},
                    {"zh": "薰衣草紫", "en": "lavender", "desc": "薰衣草紫"},
                    {"zh": "珊瑚橙", "en": "coral orange", "desc": "珊瑚橙"},
                    {"zh": "玫红", "en": "magenta", "desc": "玫红色"},
                    {"zh": "紫罗兰", "en": "violet", "desc": "紫罗兰色"},
                    {"zh": "电光蓝", "en": "electric blue", "desc": "电光蓝"},
                    {"zh": "荧光绿", "en": "neon green", "desc": "荧光绿"},
                    {"zh": "芭比粉", "en": "barbie pink", "desc": "芭比粉"},
                    {"zh": "牛油果绿", "en": "avocado green", "desc": "牛油果绿"},
                    {"zh": "香芋紫", "en": "taro purple", "desc": "香芋紫"},
                    {"zh": "奶茶色", "en": "milk tea", "desc": "奶茶色"},
                    {"zh": "脏橘色", "en": "dirty orange", "desc": "脏橘色"},
                    {"zh": "克莱因蓝", "en": "klein blue", "desc": "克莱因蓝"},
                ],
            },
            {
                "name": "马卡龙色",
                "key": "color_macaron",
                "multi": True,
                "options": [
                    {"zh": "樱花粉", "en": "cherry blossom pink", "desc": "樱花粉"},
                    {"zh": "婴儿蓝", "en": "baby blue", "desc": "婴儿蓝"},
                    {"zh": "奶油黄", "en": "cream yellow", "desc": "奶油黄"},
                    {"zh": "蜜桃色", "en": "peach", "desc": "蜜桃色"},
                    {"zh": "浅杏色", "en": "light apricot", "desc": "浅杏色"},
                    {"zh": "烟灰粉", "en": "dusty rose", "desc": "烟灰粉"},
                    {"zh": "淡紫色", "en": "lilac", "desc": "淡紫色"},
                    {"zh": "天蓝色", "en": "sky blue", "desc": "天蓝色"},
                ],
            },
            {
                "name": "大地色",
                "key": "color_earth",
                "multi": True,
                "options": [
                    {"zh": "米色", "en": "beige tone", "desc": "大地米色"},
                    {"zh": "卡其色", "en": "khaki", "desc": "卡其色"},
                    {"zh": "驼色", "en": "camel tone", "desc": "大地驼色"},
                    {"zh": "焦糖色", "en": "caramel", "desc": "焦糖色"},
                    {"zh": "深棕色", "en": "dark brown", "desc": "深棕色"},
                    {"zh": "浅棕色", "en": "light brown", "desc": "浅棕色"},
                    {"zh": "沙色", "en": "sand", "desc": "沙色"},
                    {"zh": "橄榄绿", "en": "olive green", "desc": "橄榄绿"},
                    {"zh": "巧克力色", "en": "chocolate", "desc": "巧克力色"},
                    {"zh": "太妃色", "en": "toffee", "desc": "太妃色"},
                ],
            },
            {
                "name": "配色方案",
                "key": "color_scheme",
                "multi": False,
                "options": [
                    {"zh": "同色系渐变", "en": "tonal gradient", "desc": "同色系渐变配色"},
                    {"zh": "撞色搭配", "en": "color blocking", "desc": "撞色搭配"},
                    {"zh": "三色搭配", "en": "tri-color", "desc": "三色搭配"},
                    {"zh": "黑白经典", "en": "black and white classic", "desc": "黑白经典配色"},
                    {"zh": "冷暖撞色", "en": "warm-cool contrast", "desc": "冷暖撞色配色"},
                    {"zh": "莫兰迪配色", "en": "morandi palette", "desc": "莫兰迪配色"},
                    {"zh": "马卡龙配色", "en": "macaron palette", "desc": "马卡龙配色"},
                    {"zh": "大地色搭配", "en": "earth tone palette", "desc": "大地色搭配"},
                    {"zh": "单色搭配", "en": "monochrome", "desc": "单色搭配"},
                    {"zh": "互补色搭配", "en": "complementary colors", "desc": "互补色搭配"},
                ],
            },
        ],
    },
    {
        "name": "图案/印花",
        "icon": "🖼️",
        "modules": [
            {
                "name": "图案类型",
                "key": "pattern",
                "multi": False,
                "options": [
                    {"zh": "纯色", "en": "solid color", "desc": "纯色"},
                    {"zh": "条纹", "en": "stripes", "desc": "条纹图案"},
                    {"zh": "细条纹", "en": "thin stripes", "desc": "细条纹图案"},
                    {"zh": "宽条纹", "en": "wide stripes", "desc": "宽条纹图案"},
                    {"zh": "彩虹条纹", "en": "rainbow stripes", "desc": "彩虹条纹图案"},
                    {"zh": "格纹", "en": "plaid check", "desc": "格纹图案"},
                    {"zh": "千鸟格", "en": "houndstooth", "desc": "千鸟格图案"},
                    {"zh": "苏格兰格纹", "en": "scottish tartan", "desc": "苏格兰格纹"},
                    {"zh": "维希格纹", "en": "gingham", "desc": "维希格纹图案"},
                    {"zh": "窗格纹", "en": "windowpane check", "desc": "窗格纹图案"},
                    {"zh": "碎花", "en": "small floral", "desc": "碎花印花"},
                    {"zh": "大花", "en": "large floral print", "desc": "大花印花"},
                    {"zh": "热带花卉", "en": "tropical floral", "desc": "热带花卉印花"},
                    {"zh": "玫瑰印花", "en": "rose print", "desc": "玫瑰印花"},
                    {"zh": "雏菊印花", "en": "daisy print", "desc": "雏菊印花"},
                    {"zh": "波点", "en": "polka dots", "desc": "波点图案"},
                    {"zh": "豹纹", "en": "leopard print", "desc": "豹纹图案"},
                    {"zh": "蛇纹", "en": "snake print", "desc": "蛇纹图案"},
                    {"zh": "斑马纹", "en": "zebra print", "desc": "斑马纹图案"},
                    {"zh": "迷彩", "en": "camouflage", "desc": "迷彩图案"},
                    {"zh": "扎染", "en": "tie-dye", "desc": "扎染图案"},
                    {"zh": "渐变", "en": "gradient", "desc": "渐变图案"},
                    {"zh": "字母Logo", "en": "letter logo print", "desc": "字母Logo印花"},
                    {"zh": "几何图案", "en": "geometric pattern", "desc": "几何图案"},
                    {"zh": "民族风", "en": "ethnic pattern", "desc": "民族风图案"},
                    {"zh": "佩斯利", "en": "paisley", "desc": "佩斯利图案"},
                    {"zh": "水墨晕染", "en": "ink wash", "desc": "水墨晕染图案"},
                    {"zh": "卡通印花", "en": "cartoon print", "desc": "卡通印花"},
                    {"zh": "抽象艺术", "en": "abstract art print", "desc": "抽象艺术印花"},
                    {"zh": "拼贴图案", "en": "collage pattern", "desc": "拼贴图案"},
                    {"zh": "数码印花", "en": "digital print", "desc": "数码印花"},
                    {"zh": "波西米亚印花", "en": "bohemian print", "desc": "波西米亚印花"},
                    {"zh": "中国风印花", "en": "chinese style print", "desc": "中国风印花"},
                ],
            },
        ],
    },
]
